### ISSUE TITLE
Find events by user location / entered location

### ISSUE THREAD

**Issue by javonharper** [norsepotions/tonight-services#3]
One thing that came to my mind after our discussion was that we need to know where the user currently is in order to give them the list of events.. Using the device it should be fairly simple to get the coords. However, we may need to let the server handle this. This could look something like accepting ```GET /events?lat=47.4840834443&lng=-448.84934``` as an example.

What do you think?

**Comment by reynoldsm88** [comment]
Yes it should be straightforward to take them in. For the first iteration I can simply log that I get them and return canned data for the UI development purposes.

We'll have to create a task to look into Mongo's geospatial querying to see if we can leverage that.

**Comment by javonharper** [comment]
Sound good.
